version: '3.8'
services:
    certificate_manager:
        build: .
        volumes:
            - ./:/app
        ports:
            - "5000:5000"
        environment:
            FLASK_DEBUG: 1
    #nginx: TODO: nginx as load balancer
    #    image: nginx:1.23
    #    volumes:
    #        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #    depends_on:
    #        - certificate_manager
    #    ports:
    #        - "80:80"
    # TODO: add a service for database, this would require separated Dockerfile and python scripts for the database